<a href="https://colab.research.google.com/github/MDrakib-uddin/flyrank-ml-internship/blob/main/w03_data_contract.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ML-04 — Search Intelligence Data Contract

This skeleton is yours to fill. Work the sections **in order** — each one has a one-line hint. Simple words, honest numbers.

> Working with an AI assistant? Tell it to read `skills/README.md` first and load the one skill this assignment names on its card.

## 1. Unit of analysis + time window

*One row = one what, over which dates? State it, then verify it below.*

# 1. Unit of Analysis + Time Window

**Unit of Analysis**

One row represents one content page with aggregated search and engagement metrics over a rolling 90-day observation window.

**Time Window**

The features summarize historical activity (for example, impressions, clicks, sessions, and engagement over the previous 90 days). These are the signals available when deciding whether a page should be reviewed for refresh. available at the decision time.

## 2. Fields: feature / label / context / excluded

*Sort every field you plan to touch into these four buckets. Excluded needs a why.*

# 2. Fields

## Features

- impressions_90d
- clicks_90d
- ctr
- avg_position
- engagement_rate

These are observable search and engagement signals available before making a refresh decision.

---

## Label (Proxy)

- trend_direction

For this project, pages with `trend_direction = "down"` are treated as potential refresh candidates.

---

## Context

- content_type
- main_intent
- search_volume
- competition
- content_age_days
- freshness_tier

These provide useful business context but are not direct prediction targets.

---

## Excluded

- content_id
- client_id

These fields are identifiers rather than behavioral signals. They are excluded because they could encourage memorization instead of learning general patterns.

trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

In [ ]:
features = df[
    [
        "impressions_90d",
        "clicks_90d",
        "ctr",
        "avg_position",
        "engagement_rate"
    ]
]

features.head()

   impressions_90d  clicks_90d   ctr  avg_position  engagement_rate
0             3803          29  0.76          10.6             5.88
1            15320           7  0.05          20.3             0.00
2            12581          11  0.09          36.5             0.00
3            11751          58  0.49           6.2             1.28
4            19140          24  0.13          44.0             0.00

## 3. Verify it with queries (grain, counts, missing values, windows)

*Every claim above gets a query cell here. A contract claim without a query next to it is a guess.*

In [ ]:
import pandas as pd

df = pd.read_csv("/content/content_refresh_anonymized.csv")

print("Rows:", len(df))
print("Unique content pages:", df["content_id"].nunique())

Rows: 30000
Unique content pages: 30000

In [ ]:
cols = [
    "impressions_90d",
    "clicks_90d",
    "ctr",
    "avg_position",
    "engagement_rate"
]

df[cols].isnull().sum()

impressions_90d    0
clicks_90d         0
ctr                0
avg_position       0
engagement_rate    0
dtype: int64

In [ ]:
df["trend_direction"].value_counts()

trend_direction
down      16262
stable     5962
up         4388
new        2236
flat       1152
Name: count, dtype: int64

In [ ]:
features = df[
    [
        "impressions_90d",
        "clicks_90d",
        "ctr",
        "avg_position",
        "engagement_rate"
    ]
]

features.head()

   impressions_90d  clicks_90d   ctr  avg_position  engagement_rate
0             3803          29  0.76          10.6             5.88
1            15320           7  0.05          20.3             0.00
2            12581          11  0.09          36.5             0.00
3            11751          58  0.49           6.2             1.28
4            19140          24  0.13          44.0             0.00

### impressions_90d

Available because it summarizes historical search visibility.

### clicks_90d

Available because it records previous user interactions.

### ctr

Available because it is calculated from historical impressions and clicks.

### avg_position

Available because historical ranking information is known before making a refresh decision.

### engagement_rate

Available because user engagement has already been observed.

In [ ]:
## Bad Leakege
X = features.copy()

X["leak"] = df["trend_direction"]

In [ ]:
## Good Leakege
X = X.drop(columns=["leak"])

## 4. Data limits

*What can this data never tell you? Unbalanced history, GSC-only early rows, window overlaps.*

# Data Limits

This dataset is anonymized and does not include client names, URLs, or search queries.

The target is based on observed trend categories rather than direct editorial labels.

The dataset summarizes historical performance over fixed windows and cannot establish causal relationships.

The model supports prioritization decisions and should not be interpreted as predicting Google's ranking algorithm.

## Self-check

Before you submit, confirm each line honestly:

- [ ] Every section above is filled — markdown thinking AND the code that backs it
- [ ] The notebook runs top to bottom with no errors (Runtime → Run all)
- [ ] No client names, URLs, or private queries anywhere
- [ ] My claims use careful words: observed, measured, directional, decision-support
- [ ] Committed to my repo under `work/notebooks/` — then submit your repo URL on the card. Done.